# URL подключения к базе данных
url=jdbc:postgresql://localhost:5433/kubertest

# Имя пользователя и пароль для базы данных
username=postgres
password=123

# Драйвер базы данных
classpath=./postgresql-42.7.7.jar
driver=org.postgresql.Driver

# Путь к главному файлу changelog
changeLogFile=main.xml

# Логирование
logLevel=info

# Управление проверкой логов
liquibase.hub.mode=off

