# URL подключения к базе данных
url=${LIQUIBASE_URL}

# Имя пользователя и пароль для базы данных
username=${LIQUIBASE_USERNAME}
password=${LIQUIBASE_PASSWORD}

# Драйвер базы данных
classpath=./postgresql-42.7.7.jar
driver=org.postgresql.Driver

# Путь к главному файлу changelog
changeLogFile=main.xml

# Логирование
logLevel=info

# Управление проверкой логов
liquibase.hub.mode=off

